#!/usr/bin/env bash
# Configure your Nginx server that /redirect_me
# is redirecting to another page

apt-get update
apt-get install -y nginx

mkdir /etc/nginx/html
mkdir /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html
printf %s "server {
	listen 80;
	listen [::]:80 default_server;
	root   /etc/nginx/html;
	index  index.html index.htm;

	location /redirect_me {
		return 301 Moved Permanently;
	}
}" > /etc/nginx/sites-available/default

service nginx restart
