#!/usr/bin/env bash
# Install your load balancer

apt-get install -y --no-install-recommends software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.6
apt-get update
apt-get install -y haproxy=2.6.\*

echo "ENABLED=1" > /etc/default/haproxy
mv /etc/haproxy/haproxy.cfg{,.original}
touch /etc/haproxy/haproxy.cfg

printf %s "
global
    log /dev/log local0
    log 127.0.0.1 local0 notice
    chroot /var/lib/haproxy
    maxconn 2000
    user haproxy
    group haproxy
    daemon
 
defaults
    timeout connect 10000
    timeout client 30000
    timeout server 30000
    mode http
    option redispatch
    retries 3
    log global
    option httplog

frontend my_website
    bind *:80
    mode http
    default_backend web_servers

backend web_servers
    balance roundrobin
    server 11401-web-01 18.207.224.145 check port 80
    server 11401-web-02 3.83.32.25 check port 80
" >> /etc/haproxy/haproxy.cfg
service haproxy restart
