#!/usr/bin/env bash
#Displays the content of the file "/etc/passwd"
#Sript should only display
#username
#user id
#Home directory path for the user

input="/etc/passwd"
while read -r line
do
	echo "$line"
done < "$input"

