#!/usr/bin/env bash
#Displays information about the "school" file

if [ -e "school" ]
then
	echo "School file exists"
	if [ -s "school" ]
	then 
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi

	if [ -f "school" ]
	then
		echo "school is a regular file"
	fi
else
	echo "School file does not exist"
fi
