#!/usr/bin/env bash
# Firewall. Block all incoming traffic except the following TCP ports
#	22(SSH)
#	443 (HTTPS SSL)
#	80(HTTP)

apt install ufw
ufw default deny incoming
ufw default allow outgoing
ufw allow 22
ufw allow 443
ufw allow 80
ufw allow from 8080 to any port 80
ufw enable
