#!/usr/bin/env bash
# Serve page from the route /airbnb-onepage/


server {
  listen      80 default_server;
  listen      [::]:80 default_server;
  
  server_name 18.207.224.145;

  location = /airbnb-onepage/ {
     proxy_pass http://127.0.0.1:5000/airbnb-onepage/;     
  }
  location ~ /airbnb-dynamic/number_odd_or_even/(\d+)$ {
      proxy_pass http://127.0.0.1:5001/number_odd_or_even/$1;
  }
  location /api {
      proxy_pass http://127.0.0.1:5002/api;
  }

  error_page 404 /404.html;
  location /404 {
    root /var/www/html;
    internal;
  }
}

